#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using NUnit.Framework;
using Splatoon.Combat;
using Splatoon.Prototype;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using Object = UnityEngine.Object;

namespace Splatoon.Tests
{
    // Opt-in evidence generated by the real Boot/Host Play Mode acceptance test.
    internal static class SplooshSummerPlayEvidence
    {
        const string Output = "Reports/SplooshGirlSummer";

        public static void CaptureTransitions(PrototypePlayer player)
        {
            Directory.CreateDirectory(Output);
            var view = player.CharacterView;
            var state = player.Snapshot.Value;
            state.Revision++; state.Yaw = state.BodyYaw = 0;
            view.transform.rotation = Quaternion.identity;
            float maxGrip = 0, maxAim = 0; int frames = 0;
            double now = 100;
            string[] stages = { "idle", "forward-fire", "backward-fire", "left-fire", "right-fire",
                "turn-left", "turn-right", "air", "aim-up", "aim-down", "death-forward", "respawn-forward",
                "death-backward", "respawn-backward", "swim", "swim-death", "respawn-swim" };
            foreach (string stage in stages)
            {
                bool dead = stage.StartsWith("death") || stage == "swim-death";
                state.Health = dead ? 0 : 100; state.Swimming = stage.StartsWith("swim");
                state.CompactBody = state.Swimming; state.Grounded = stage != "air";
                state.Velocity = stage == "forward-fire" ? Vector3.forward * 4 : stage == "backward-fire" ? Vector3.back * 4 :
                    stage == "left-fire" ? Vector3.left * 4 : stage == "right-fire" ? Vector3.right * 4 : Vector3.zero;
                state.Firing = stage.EndsWith("fire"); state.FireStartedAt = now;
                state.TurnDirection = (sbyte)(stage == "turn-left" ? -1 : stage == "turn-right" ? 1 : 0);
                state.TurnStartedAt = state.DiedAt = now;
                state.DeathDirection = (byte)(stage == "death-forward" ? 1 : 0);
                state.Pitch = stage == "aim-up" ? -65 : stage == "aim-down" ? 75 : 0;
                if (stage.StartsWith("respawn")) state.Revision++;
                for (int frame = 0; frame < 60; frame++)
                {
                    now += 1.0 / 60;
                    view.Present(state, 1f / 60, now);
                    if (view.Animator.enabled) { view.Animator.Update(1f / 60); view.ApplyAim(); }
                    if (!dead && !state.Swimming)
                    {
                        float grip = Vector3.Distance(view.Animator.GetBoneTransform(HumanBodyBones.LeftHand).position, view.LeftGrip.position);
                        float aim = Vector3.Angle(view.Nozzle.forward, Quaternion.Euler(state.Pitch, state.Yaw, 0) * Vector3.forward);
                        maxGrip = Mathf.Max(maxGrip, grip); maxAim = Mathf.Max(maxAim, aim);
                        Assert.That(grip, Is.LessThan(.01f), stage + " support grip");
                        Assert.That(aim, Is.LessThan(.1f), stage + " muzzle direction");
                    }
                    frames++;
                    if (frame == 15 || frame == 50)
                        Capture(view.transform.position + Vector3.up * .75f, "transition-" + stage + "-" + frame);
                }
                if (stage.StartsWith("respawn"))
                {
                    Assert.That(view.Animator.enabled, Is.True);
                    Assert.That(view.Animator.GetCurrentAnimatorStateInfo(0).IsName("Base Layer.Locomotion"), Is.True, stage);
                    Assert.That(view.Animator.GetLayerWeight(1), Is.Zero, stage + " clears shooting");
                }
                if (dead) Assert.That(view.Animator.GetCurrentAnimatorStateInfo(0).IsName(
                    state.DeathDirection == 1 ? "Base Layer.DieForward" : "Base Layer.DieBackward"), Is.True, stage);
                if (stage == "swim") Assert.That(view.Animator.enabled, Is.False);
            }
            File.WriteAllText(Output + "/transitions.json", FormattableString.Invariant(
                $"{{\"stages\":{stages.Length},\"frames\":{frames},\"maxGripErrorMetres\":{maxGrip:R},\"maxMuzzleAngleDegrees\":{maxAim:R},\"playMode\":true}}"));
        }

        public static void CaptureHitVolumes(PrototypePlayer player)
        {
            var state = player.Snapshot.Value;
            state.Yaw = state.BodyYaw = state.Pitch = 0; state.Revision++;
            var view = player.CharacterView;
            var body = player.SwimBody;
            player.GetComponent<CharacterController>().enabled = false;
            view.transform.rotation = Quaternion.identity;
            foreach (bool paper in new[] { false, true })
            {
                state.Swimming = state.CompactBody = paper;
                state.Movement = paper ? MovementMode.GroundInk : MovementMode.Human;
                state.SwimSource = SwimSurface.Friendly;
                state.PaperPose = PaperPose.None;
                if (paper) PaperPoseSimulation.Resolve(ref state, default, body.Profile, 100);
                body.ApplyCollision(state); body.Present(state, Vector3.zero, Quaternion.identity);
                view.Present(state, .1f, 100);
                if (view.Animator.enabled) { view.Animator.Update(.1f); view.ApplyAim(); }
                var lines = new GameObject("Measured hit geometry");
                var material = new Material(Shader.Find("Universal Render Pipeline/Unlit"));
                material.SetColor("_BaseColor", Color.cyan);
                void Line(IEnumerable<Vector3> points, bool loop)
                {
                    var go = new GameObject("Hit outline"); go.transform.SetParent(lines.transform);
                    var line = go.AddComponent<LineRenderer>(); line.sharedMaterial = material;
                    line.useWorldSpace = true; line.loop = loop; line.widthMultiplier = .005f;
                    var positions = points.ToArray(); line.positionCount = positions.Length; line.SetPositions(positions);
                }
                try
                {
                    if (paper)
                    {
                        Assert.That(body.FlatHitActive, Is.True);
                        foreach (var rect in body.HitRects)
                            Line(new[] { new Vector3(rect.xMin,rect.yMin,-.006f), new Vector3(rect.xMax,rect.yMin,-.006f),
                                new Vector3(rect.xMax,rect.yMax,-.006f), new Vector3(rect.xMin,rect.yMax,-.006f) }
                                .Select(p => body.HitVolume.transform.TransformPoint(p)), true);
                    }
                    else
                    {
                        var capsule = body.CapsuleHitVolume;
                        Assert.That(capsule.enabled, Is.True); Assert.That(capsule.height, Is.EqualTo(1.5f));
                        float radius = capsule.radius, straight = capsule.height * .5f - radius;
                        foreach (Vector3 axis in new[] { Vector3.right, Vector3.forward })
                        {
                            var points = new List<Vector3>();
                            for (int i=0;i<=24;i++) { float a=Mathf.PI*i/24; points.Add(capsule.center+Vector3.up*(straight+radius*Mathf.Sin(a))+axis*(radius*Mathf.Cos(a))); }
                            for (int i=0;i<=24;i++) { float a=Mathf.PI+Mathf.PI*i/24; points.Add(capsule.center+Vector3.up*(-straight+radius*Mathf.Sin(a))+axis*(radius*Mathf.Cos(a))); }
                            Line(points.Select(p=>capsule.transform.TransformPoint(p)),true);
                        }
                    }
                    Capture(paper ? state.PaperCenter : state.Position + Vector3.up * .75f, paper ? "hit-paper" : "hit-standing", paper);
                }
                finally { Object.DestroyImmediate(lines); Object.DestroyImmediate(material); }
            }
        }

        static void Capture(Vector3 target, string name, bool top = false)
        {
            Assert.That(SystemInfo.graphicsDeviceType, Is.Not.EqualTo(GraphicsDeviceType.Null));
            // These states advance explicitly within one Play Mode frame. Freeze the
            // evaluated skin so the render request cannot reuse the earlier skin cache.
            var skins = Object.FindObjectsByType<SkinnedMeshRenderer>(FindObjectsSortMode.None)
                .Where(s => s.enabled && s.gameObject.activeInHierarchy).ToArray();
            var frozen = new List<GameObject>(); var meshes = new List<Mesh>();
            foreach (var skin in skins)
            {
                var mesh = new Mesh(); skin.BakeMesh(mesh); meshes.Add(mesh);
                var go = new GameObject("Evaluated Play Mode skin"); go.layer = skin.gameObject.layer;
                go.transform.SetPositionAndRotation(skin.transform.position, skin.transform.rotation);
                go.transform.localScale = skin.transform.lossyScale;
                go.AddComponent<MeshFilter>().sharedMesh = mesh;
                go.AddComponent<MeshRenderer>().sharedMaterials = skin.sharedMaterials;
                frozen.Add(go); skin.enabled = false;
            }
            var camera = new GameObject("Summer rendered evidence").AddComponent<Camera>();
            camera.CopyFrom(Camera.main); camera.enabled = false; camera.aspect = 1; camera.fieldOfView = 38;
            camera.GetUniversalAdditionalCameraData().renderPostProcessing = false;
            camera.transform.position = target + (top ? new Vector3(0, 2.6f, .6f) : new Vector3(1.5f, .4f, 2.3f));
            camera.transform.LookAt(target);
            var rt = new RenderTexture(960,960,24); rt.Create(); var prior = RenderTexture.active;
            var image = new Texture2D(960,960,TextureFormat.RGB24,false);
            try
            {
                camera.targetTexture = rt;
                RenderPipeline.SubmitRenderRequest(camera,new UniversalRenderPipeline.SingleCameraRequest { destination=rt });
                RenderTexture.active=rt; image.ReadPixels(new Rect(0,0,960,960),0,0); image.Apply();
                File.WriteAllBytes(Output + "/" + name + ".png",image.EncodeToPNG());
            }
            finally
            {
                RenderTexture.active=prior; rt.Release(); Object.DestroyImmediate(camera.gameObject); Object.DestroyImmediate(rt); Object.DestroyImmediate(image);
                foreach (var skin in skins) skin.enabled = true;
                foreach (var go in frozen) Object.DestroyImmediate(go);
                foreach (var mesh in meshes) Object.DestroyImmediate(mesh);
            }
        }
    }
}
#endif
