using System;
using System.IO;

namespace Splatoon.Config
{
    /// <summary>Immutable values shared by simulation and the shots emitted under this configuration.</summary>
    public sealed class WeaponRuntimeConfig
    {
        public readonly string WeaponPrefabAddress;
        public readonly WeaponFireMode FireMode;
        public readonly float FireRate;
        public readonly float ShotInk;
        public readonly double StartSeconds;
        public readonly double EmergeStartSeconds;
        public readonly double InkRecoverLockSeconds;
        public readonly float ShootMoveSpeed;
        public readonly int BurstCount;
        public readonly double BurstRecoverySeconds;
        public readonly float SpeedMin;
        public readonly float SpeedMax;
        public readonly float ProjectileGravity;
        public readonly float Lifetime;
        public readonly float CollisionRadius;
        public readonly float SpreadDegrees;
        public readonly double StraightSeconds;
        public readonly double BrakeSeconds;
        public readonly float BrakeSpeedMultiplier;
        public readonly float JumpSpreadDegrees;
        public readonly double LandingSpreadRecoverSeconds;
        public readonly float EffectiveRange;
        public readonly float Damage;
        public readonly float DamageMin;
        public readonly double DamageReduceStartSeconds;
        public readonly double DamageReduceEndSeconds;
        public readonly float PaintRadiusMin;
        public readonly float PaintRadiusMax;
        public readonly float PaintHardness;
        public readonly float PaintStrength;
        public readonly float TrailSpacing;
        public readonly float TrailRadiusMin;
        public readonly float TrailRadiusMax;
        public readonly float TrailMaxDrop;
        public readonly double ChargeSeconds;
        public readonly float ChargeMinDamage;
        public readonly float ChargePartialMaxDamage;
        public readonly float ChargeMinInk;
        public readonly float ChargeMinRange;
        public readonly float ChargeMinSpeed;
        public readonly float ChargeMinSpread;
        public readonly float ChargeMinJumpSpread;
        public readonly int PelletCount;
        public readonly WeaponMuzzleMode MuzzleMode;
        public readonly double SemiBufferSeconds;
        public readonly double SplatlingMinChargeSeconds;
        public readonly double SplatlingFirstChargeSeconds;
        public readonly double SplatlingFirstShootSeconds;
        public readonly double SplatlingFullShootSeconds;
        public readonly float SplatlingSlowChargeMultiplier;
        public readonly float SplatlingChargeMoveSpeed;
        public readonly float SplatlingChargeJumpSpeed;
        public readonly double SplatlingPostSeconds;
        public readonly float SplatlingPitchSpread;
        public readonly float SplatlingSpreadBias;
        public readonly float SplatlingSpeedBias;
        public readonly int SplatlingFootEvery;
        public readonly int SplatlingTrailCount;
        public readonly float SplatlingFootRadius;
        public readonly float SplatlingPlayerRadius;
        public readonly float SpreadExpandSeconds;
        public readonly float SpreadRecoverSeconds;
        public readonly float BaseSpreadDegrees;
        public readonly float BaseJumpSpreadDegrees;
        public readonly ProjectileMotionMode MotionMode;
        public readonly double BubbleVolleySeconds;
        public readonly double BubbleIntervalSeconds;
        public readonly int BubbleGroundBounces;
        public readonly int BubbleMaxBounces;
        public readonly float BubbleNormalRetention;
        public readonly float BubbleTangentRetention;
        public readonly float BubbleWallRetention;
        public readonly double BlasterRepeatSeconds;
        public readonly double BlasterPostSeconds;
        public readonly float BlasterPlayerRadius;
        public readonly float BlasterBrakeEndSpeed;
        public readonly float BlasterBrakeDrag;
        public readonly float BlasterBrakeGravity;
        public readonly int BlasterTrailCount;
        public readonly float DualiesBrakeEndSpeed;
        public readonly float DualiesBrakeDrag;
        public readonly float DualiesBrakeGravity;
        public readonly float DualiesPlayerRadius;
        public readonly float DualiesSpreadMinBias;
        public readonly float DualiesSpreadMaxBias;
        public readonly float DualiesSpreadPerShot;
        public readonly float DualiesSpreadRecoverPerSecond;
        public readonly float DualiesJumpBias;
        public readonly double DualiesJumpRecoverStartSeconds;
        public readonly double DualiesJumpRecoverEndSeconds;
        public readonly float DualiesTrailStartDistance;
        public readonly int DualiesTrailCount;
        public readonly int DualiesFootEvery;
        public readonly float DualiesFootRadius;
        public readonly bool ReferenceRules;
        public readonly float ReferenceBrakeEndSpeed;
        public readonly float ReferenceBrakeDrag;
        public readonly float ReferenceBrakeGravity;
        public readonly float ReferenceFreeDrag;
        public readonly float ReferencePlayerRadius;
        public readonly bool ReferenceSpreadEnabled;
        public readonly float ReferenceBiasMin;
        public readonly float ReferenceBiasMax;
        public readonly float ReferenceBiasPerShot;
        public readonly float ReferenceBiasRecovery;
        public readonly float ReferenceJumpBias;
        public readonly double ReferenceJumpStart;
        public readonly double ReferenceJumpEnd;
        public readonly float ReferencePitchBias;
        public readonly float ReferenceTrailBudget;
        public readonly float ReferenceTrailStart;
        public readonly bool ReferenceTrailRandomPhase;
        public readonly int ReferenceFootEvery;
        public readonly float ReferenceFootRadius;
        public readonly float ReferenceFootDepth;
        public readonly float PaintDepthMin;
        public readonly float PaintDepthMax;
        public readonly float PaintDepthBreakMin;
        public readonly float PaintDepthBreakMax;
        public readonly float PaintDistanceMiddle;
        public readonly float PaintDistanceFar;
        public readonly float PaintBreakHeight;
        public readonly float TrailDepthScale;
        public readonly float PaintDropGravity;
        public readonly float PaintDropLifetime;
        public readonly float WallDropRadius;
        public readonly float WallDropGroundRadius;
        public readonly float WallDropSpeed;
        public readonly double WallDropSeconds;
        public readonly float CollisionExplosionPaintRadius;
        public readonly float BubbleAirSpeed;
        public readonly float BubbleLaterSpeed;
        public readonly float BubbleLaterAirSpeed;
        public readonly float BubbleSpeedDecrement;
        public readonly float BubbleUpwardRate;
        public readonly float BubbleInitialRadiusRate;
        public readonly double BubbleFieldGrowSeconds;
        public readonly double BubblePlayerGrowSeconds;
        public readonly float BubbleLaterFieldRadius;
        public readonly float BubbleLaterPlayerRadius;
        public readonly float BubbleRadiusDecrement;
        public readonly float BubbleBounceRadiusRate;
        public readonly float BubbleBouncePaintRate;
        public readonly float BubbleFirstBouncePaintRadius;
        public readonly float BubbleLaterBouncePaintRadius;
        public readonly float BubbleBouncePaintDecrement;
        public readonly float BubbleLaterImpactRadius;
        public readonly AmmoRuntimeConfig Ammo;
        public readonly float ExplosherAirSpeed;
        public readonly float ExplosherUpwardRate;
        public readonly float ExplosherMoveSideRate;
        public readonly float ExplosherMoveForwardRate;
        public readonly float ExplosherMoveVerticalRate;
        public readonly float ExplosherFieldInitialRadius;
        public readonly float ExplosherPlayerInitialRadius;
        public readonly double ExplosherFieldGrowSeconds;
        public readonly double ExplosherPlayerGrowSeconds;
        public readonly double ExplosherPostSeconds;
        public readonly double ExplosherMoveLimitSeconds;
        public readonly float ExplosherPaintNearDistance;
        public readonly float ExplosherPaintFarDistance;
        public readonly float ExplosherBlastOffset;
        public readonly float ExplosherTrailPhaseMax;
        public readonly float ExplosherFootDepth;
        public readonly bool ShooterDetails;
        public readonly double ShooterPostSeconds;
        public readonly float ShooterMoveForwardRate;
        public readonly float ShooterPaintNearDistance;
        public readonly float ShooterPaintNearRadius;
        public readonly float ShooterPaintAngleMin;
        public readonly float ShooterPaintAngleMax;
        public readonly float ShooterFallHeightMin;
        public readonly float ShooterFallHeightMax;
        public readonly int ShooterSplitNum;
        public readonly float ShooterSplashDepthMin;
        public readonly float ShooterSplashDepthMax;
        public readonly float ShooterSplashHeightMin;
        public readonly float ShooterSplashHeightMax;
        public readonly float ShooterSplashSideSpeed;
        public readonly float ShooterSplashUpSpeed;
        public readonly float ShooterSplashForwardMin;
        public readonly float ShooterSplashForwardMax;
        public readonly double ShooterWallFirstMin;
        public readonly double ShooterWallFirstMax;
        public readonly double ShooterWallMiddle;
        public readonly double ShooterWallLastMin;
        public readonly double ShooterWallLastMax;
        public readonly float ShooterWallFirstSpeed;
        public readonly float ShooterWallGravity;
        public readonly float ShooterWallShockRadius;
        public WeaponRuntimeConfig(WeaponConfigAsset source)
        {
            ShooterDetails = source.shooterDetails;
            ShooterPostSeconds = source.shooterPostSeconds;
            ShooterMoveForwardRate = source.shooterMoveForwardRate;
            ShooterPaintNearDistance = source.shooterPaintNearDistance;
            ShooterPaintNearRadius = source.shooterPaintNearRadius;
            ShooterPaintAngleMin = source.shooterPaintAngleMin;
            ShooterPaintAngleMax = source.shooterPaintAngleMax;
            ShooterFallHeightMin = source.shooterFallHeightMin;
            ShooterFallHeightMax = source.shooterFallHeightMax;
            ShooterSplitNum = source.shooterSplitNum;
            ShooterSplashDepthMin = source.shooterSplashDepthMin;
            ShooterSplashDepthMax = source.shooterSplashDepthMax;
            ShooterSplashHeightMin = source.shooterSplashHeightMin;
            ShooterSplashHeightMax = source.shooterSplashHeightMax;
            ShooterSplashSideSpeed = source.shooterSplashSideSpeed;
            ShooterSplashUpSpeed = source.shooterSplashUpSpeed;
            ShooterSplashForwardMin = source.shooterSplashForwardMin;
            ShooterSplashForwardMax = source.shooterSplashForwardMax;
            ShooterWallFirstMin = source.shooterWallFirstMin;
            ShooterWallFirstMax = source.shooterWallFirstMax;
            ShooterWallMiddle = source.shooterWallMiddle;
            ShooterWallLastMin = source.shooterWallLastMin;
            ShooterWallLastMax = source.shooterWallLastMax;
            ShooterWallFirstSpeed = source.shooterWallFirstSpeed;
            ShooterWallGravity = source.shooterWallGravity;
            ShooterWallShockRadius = source.shooterWallShockRadius;
            ExplosherAirSpeed = source.explosherAirSpeed;
            ExplosherUpwardRate = source.explosherUpwardRate;
            ExplosherMoveSideRate = source.explosherMoveSideRate;
            ExplosherMoveForwardRate = source.explosherMoveForwardRate;
            ExplosherMoveVerticalRate = source.explosherMoveVerticalRate;
            ExplosherFieldInitialRadius = source.explosherFieldInitialRadius;
            ExplosherPlayerInitialRadius = source.explosherPlayerInitialRadius;
            ExplosherFieldGrowSeconds = source.explosherFieldGrowSeconds;
            ExplosherPlayerGrowSeconds = source.explosherPlayerGrowSeconds;
            ExplosherPostSeconds = source.explosherPostSeconds;
            ExplosherMoveLimitSeconds = source.explosherMoveLimitSeconds;
            ExplosherPaintNearDistance = source.explosherPaintNearDistance;
            ExplosherPaintFarDistance = source.explosherPaintFarDistance;
            ExplosherBlastOffset = source.explosherBlastOffset;
            ExplosherTrailPhaseMax = source.explosherTrailPhaseMax;
            ExplosherFootDepth = source.explosherFootDepth;

            ReferenceRules = source.referenceRules;
            ReferenceBrakeEndSpeed = source.referenceBrakeEndSpeed;
            ReferenceBrakeDrag = source.referenceBrakeDrag;
            ReferenceBrakeGravity = source.referenceBrakeGravity;
            ReferenceFreeDrag = source.referenceFreeDrag;
            ReferencePlayerRadius = source.referencePlayerRadius;
            ReferenceSpreadEnabled = source.referenceSpreadEnabled;
            ReferenceBiasMin = source.referenceBiasMin;
            ReferenceBiasMax = source.referenceBiasMax;
            ReferenceBiasPerShot = source.referenceBiasPerShot;
            ReferenceBiasRecovery = source.referenceBiasRecovery;
            ReferenceJumpBias = source.referenceJumpBias;
            ReferenceJumpStart = source.referenceJumpStart;
            ReferenceJumpEnd = source.referenceJumpEnd;
            ReferencePitchBias = source.referencePitchBias;
            ReferenceTrailBudget = source.referenceTrailBudget;
            ReferenceTrailStart = source.referenceTrailStart;
            ReferenceTrailRandomPhase = source.referenceTrailRandomPhase;
            ReferenceFootEvery = source.referenceFootEvery;
            ReferenceFootRadius = source.referenceFootRadius;
            ReferenceFootDepth = source.referenceFootDepth;
            PaintDepthMin = source.paintDepthMin;
            PaintDepthMax = source.paintDepthMax;
            PaintDepthBreakMin = source.paintDepthBreakMin;
            PaintDepthBreakMax = source.paintDepthBreakMax;
            PaintDistanceMiddle = source.paintDistanceMiddle;
            PaintDistanceFar = source.paintDistanceFar;
            PaintBreakHeight = source.paintBreakHeight;
            TrailDepthScale = source.trailDepthScale;
            PaintDropGravity = source.paintDropGravity;
            PaintDropLifetime = source.paintDropLifetime;
            WallDropRadius = source.wallDropRadius;
            WallDropGroundRadius = source.wallDropGroundRadius;
            WallDropSpeed = source.wallDropSpeed;
            WallDropSeconds = source.wallDropSeconds;
            CollisionExplosionPaintRadius = source.collisionExplosionPaintRadius;
            BubbleAirSpeed = source.bubbleAirSpeed;
            BubbleLaterSpeed = source.bubbleLaterSpeed;
            BubbleLaterAirSpeed = source.bubbleLaterAirSpeed;
            BubbleSpeedDecrement = source.bubbleSpeedDecrement;
            BubbleUpwardRate = source.bubbleUpwardRate;
            BubbleInitialRadiusRate = source.bubbleInitialRadiusRate;
            BubbleFieldGrowSeconds = source.bubbleFieldGrowSeconds;
            BubblePlayerGrowSeconds = source.bubblePlayerGrowSeconds;
            BubbleLaterFieldRadius = source.bubbleLaterFieldRadius;
            BubbleLaterPlayerRadius = source.bubbleLaterPlayerRadius;
            BubbleRadiusDecrement = source.bubbleRadiusDecrement;
            BubbleBounceRadiusRate = source.bubbleBounceRadiusRate;
            BubbleBouncePaintRate = source.bubbleBouncePaintRate;
            BubbleFirstBouncePaintRadius = source.bubbleFirstBouncePaintRadius;
            BubbleLaterBouncePaintRadius = source.bubbleLaterBouncePaintRadius;
            BubbleBouncePaintDecrement = source.bubbleBouncePaintDecrement;
            BubbleLaterImpactRadius = source.bubbleLaterImpactRadius;
            DualiesBrakeEndSpeed = source.dualiesBrakeEndSpeed;
            DualiesBrakeDrag = source.dualiesBrakeDrag;
            DualiesBrakeGravity = source.dualiesBrakeGravity;
            DualiesPlayerRadius = source.dualiesPlayerRadius;
            DualiesSpreadMinBias = source.dualiesSpreadMinBias;
            DualiesSpreadMaxBias = source.dualiesSpreadMaxBias;
            DualiesSpreadPerShot = source.dualiesSpreadPerShot;
            DualiesSpreadRecoverPerSecond = source.dualiesSpreadRecoverPerSecond;
            DualiesJumpBias = source.dualiesJumpBias;
            DualiesJumpRecoverStartSeconds = source.dualiesJumpRecoverStartSeconds;
            DualiesJumpRecoverEndSeconds = source.dualiesJumpRecoverEndSeconds;
            DualiesTrailStartDistance = source.dualiesTrailStartDistance;
            DualiesTrailCount = source.dualiesTrailCount;
            DualiesFootEvery = source.dualiesFootEvery;
            DualiesFootRadius = source.dualiesFootRadius;
            BlasterRepeatSeconds = source.blasterRepeatSeconds;
            BlasterPostSeconds = source.blasterPostSeconds;
            BlasterPlayerRadius = source.blasterPlayerRadius;
            BlasterBrakeEndSpeed = source.blasterBrakeEndSpeed;
            BlasterBrakeDrag = source.blasterBrakeDrag;
            BlasterBrakeGravity = source.blasterBrakeGravity;
            BlasterBrakeGravity = source.blasterBrakeGravity;
            BlasterTrailCount = source.blasterTrailCount;
            MotionMode = source.motionMode;
            BubbleVolleySeconds = source.bubbleVolleySeconds;
            BubbleIntervalSeconds = source.bubbleIntervalSeconds;
            BubbleGroundBounces = source.bubbleGroundBounces;
            BubbleMaxBounces = source.bubbleMaxBounces;
            BubbleNormalRetention = source.bubbleNormalRetention;
            BubbleTangentRetention = source.bubbleTangentRetention;
            BubbleWallRetention = source.bubbleWallRetention;
            Ammo = new AmmoRuntimeConfig(source != null ? source.ammoConfig : null);
            WeaponPrefabAddress = source.weaponPrefabAddress;
            FireMode = source.fireMode;
            FireRate = source.fireMode == WeaponFireMode.Blaster && source.blasterRepeatSeconds > 0
                ? (float)(1.0 / source.blasterRepeatSeconds) : source.fireRate;
            ShotInk = source.shotInk;
            StartSeconds = source.startSeconds;
            EmergeStartSeconds = source.emergeStartSeconds;
            InkRecoverLockSeconds = source.inkRecoverLockSeconds;
            ShootMoveSpeed = source.shootMoveSpeed;
            BurstCount = source.burstCount;
            BurstRecoverySeconds = source.burstRecoverySeconds;
            SpeedMin = source.speedMin;
            SpeedMax = source.speedMax;
            ProjectileGravity = source.projectileGravity;
            Lifetime = source.lifetime;
            CollisionRadius = source.collisionRadius;
            SpreadDegrees = source.spreadDegrees;
            StraightSeconds = source.straightSeconds;
            BrakeSeconds = source.brakeSeconds;
            BrakeSpeedMultiplier = source.brakeSpeedMultiplier;
            JumpSpreadDegrees = source.jumpSpreadDegrees;
            LandingSpreadRecoverSeconds = source.landingSpreadRecoverSeconds;
            EffectiveRange = source.effectiveRange;
            Damage = source.damage;
            DamageMin = source.damageMin;
            DamageReduceStartSeconds = source.damageReduceStartSeconds;
            DamageReduceEndSeconds = source.damageReduceEndSeconds;
            PaintRadiusMin = source.paintRadiusMin;
            PaintRadiusMax = source.paintRadiusMax;
            PaintHardness = source.paintHardness;
            PaintStrength = source.paintStrength;
            TrailSpacing = source.trailSpacing;
            TrailRadiusMin = source.trailRadiusMin;
            TrailRadiusMax = source.trailRadiusMax;
            TrailMaxDrop = source.trailMaxDrop;
            ChargeSeconds = source.chargeSeconds;
            ChargeMinDamage = source.chargeMinDamage;
            ChargePartialMaxDamage = source.chargePartialMaxDamage;
            ChargeMinInk = source.chargeMinInk;
            ChargeMinRange = source.chargeMinRange;
            ChargeMinSpeed = source.chargeMinSpeed;
            ChargeMinSpread = source.chargeMinSpread;
            ChargeMinJumpSpread = source.chargeMinJumpSpread;
            PelletCount = source.pelletCount;
            MuzzleMode = source.muzzleMode;
            SemiBufferSeconds = source.semiBufferSeconds;
            SplatlingMinChargeSeconds = source.splatlingMinChargeSeconds;
            SplatlingFirstChargeSeconds = source.splatlingFirstChargeSeconds;
            SplatlingFirstShootSeconds = source.splatlingFirstShootSeconds;
            SplatlingFullShootSeconds = source.splatlingFullShootSeconds;
            SplatlingSlowChargeMultiplier = source.splatlingSlowChargeMultiplier;
            SplatlingChargeMoveSpeed = source.splatlingChargeMoveSpeed;
            SplatlingChargeJumpSpeed = source.splatlingChargeJumpSpeed;
            SplatlingPostSeconds = source.splatlingPostSeconds;
            SplatlingPitchSpread = source.splatlingPitchSpread;
            SplatlingSpreadBias = source.splatlingSpreadBias;
            SplatlingSpeedBias = source.splatlingSpeedBias;
            SplatlingFootEvery = source.splatlingFootEvery;
            SplatlingTrailCount = source.splatlingTrailCount;
            SplatlingFootRadius = source.splatlingFootRadius;
            SplatlingPlayerRadius = source.splatlingPlayerRadius;
            SpreadExpandSeconds = source.spreadExpandSeconds;
            SpreadRecoverSeconds = source.spreadRecoverSeconds;
            BaseSpreadDegrees = source.baseSpreadDegrees;
            BaseJumpSpreadDegrees = source.baseJumpSpreadDegrees;
        }
        public void Write(BinaryWriter writer)
        {
            writer.Write(ShooterDetails);
            writer.Write(ShooterPostSeconds);
            writer.Write(ShooterMoveForwardRate);
            writer.Write(ShooterPaintNearDistance);
            writer.Write(ShooterPaintNearRadius);
            writer.Write(ShooterPaintAngleMin);
            writer.Write(ShooterPaintAngleMax);
            writer.Write(ShooterFallHeightMin);
            writer.Write(ShooterFallHeightMax);
            writer.Write(ShooterSplitNum);
            writer.Write(ShooterSplashDepthMin);
            writer.Write(ShooterSplashDepthMax);
            writer.Write(ShooterSplashHeightMin);
            writer.Write(ShooterSplashHeightMax);
            writer.Write(ShooterSplashSideSpeed);
            writer.Write(ShooterSplashUpSpeed);
            writer.Write(ShooterSplashForwardMin);
            writer.Write(ShooterSplashForwardMax);
            writer.Write(ShooterWallFirstMin);
            writer.Write(ShooterWallFirstMax);
            writer.Write(ShooterWallMiddle);
            writer.Write(ShooterWallLastMin);
            writer.Write(ShooterWallLastMax);
            writer.Write(ShooterWallFirstSpeed);
            writer.Write(ShooterWallGravity);
            writer.Write(ShooterWallShockRadius);
            writer.Write(ExplosherAirSpeed);
            writer.Write(ExplosherUpwardRate);
            writer.Write(ExplosherMoveSideRate);
            writer.Write(ExplosherMoveForwardRate);
            writer.Write(ExplosherMoveVerticalRate);
            writer.Write(ExplosherFieldInitialRadius);
            writer.Write(ExplosherPlayerInitialRadius);
            writer.Write(ExplosherFieldGrowSeconds);
            writer.Write(ExplosherPlayerGrowSeconds);
            writer.Write(ExplosherPostSeconds);
            writer.Write(ExplosherMoveLimitSeconds);
            writer.Write(ExplosherPaintNearDistance);
            writer.Write(ExplosherPaintFarDistance);
            writer.Write(ExplosherBlastOffset);
            writer.Write(ExplosherTrailPhaseMax);
            writer.Write(ExplosherFootDepth);

            writer.Write(ReferenceRules);
            writer.Write(ReferenceBrakeEndSpeed);
            writer.Write(ReferenceBrakeDrag);
            writer.Write(ReferenceBrakeGravity);
            writer.Write(ReferenceFreeDrag);
            writer.Write(ReferencePlayerRadius);
            writer.Write(ReferenceSpreadEnabled);
            writer.Write(ReferenceBiasMin);
            writer.Write(ReferenceBiasMax);
            writer.Write(ReferenceBiasPerShot);
            writer.Write(ReferenceBiasRecovery);
            writer.Write(ReferenceJumpBias);
            writer.Write(ReferenceJumpStart);
            writer.Write(ReferenceJumpEnd);
            writer.Write(ReferencePitchBias);
            writer.Write(ReferenceTrailBudget);
            writer.Write(ReferenceTrailStart);
            writer.Write(ReferenceTrailRandomPhase);
            writer.Write(ReferenceFootEvery);
            writer.Write(ReferenceFootRadius);
            writer.Write(ReferenceFootDepth);
            writer.Write(PaintDepthMin);
            writer.Write(PaintDepthMax);
            writer.Write(PaintDepthBreakMin);
            writer.Write(PaintDepthBreakMax);
            writer.Write(PaintDistanceMiddle);
            writer.Write(PaintDistanceFar);
            writer.Write(PaintBreakHeight);
            writer.Write(TrailDepthScale);
            writer.Write(PaintDropGravity);
            writer.Write(PaintDropLifetime);
            writer.Write(WallDropRadius);
            writer.Write(WallDropGroundRadius);
            writer.Write(WallDropSpeed);
            writer.Write(WallDropSeconds);
            writer.Write(CollisionExplosionPaintRadius);
            writer.Write(BubbleAirSpeed);
            writer.Write(BubbleLaterSpeed);
            writer.Write(BubbleLaterAirSpeed);
            writer.Write(BubbleSpeedDecrement);
            writer.Write(BubbleUpwardRate);
            writer.Write(BubbleInitialRadiusRate);
            writer.Write(BubbleFieldGrowSeconds);
            writer.Write(BubblePlayerGrowSeconds);
            writer.Write(BubbleLaterFieldRadius);
            writer.Write(BubbleLaterPlayerRadius);
            writer.Write(BubbleRadiusDecrement);
            writer.Write(BubbleBounceRadiusRate);
            writer.Write(BubbleBouncePaintRate);
            writer.Write(BubbleFirstBouncePaintRadius);
            writer.Write(BubbleLaterBouncePaintRadius);
            writer.Write(BubbleBouncePaintDecrement);
            writer.Write(BubbleLaterImpactRadius);
            writer.Write(DualiesBrakeEndSpeed);
            writer.Write(DualiesBrakeDrag);
            writer.Write(DualiesBrakeGravity);
            writer.Write(DualiesPlayerRadius);
            writer.Write(DualiesSpreadMinBias);
            writer.Write(DualiesSpreadMaxBias);
            writer.Write(DualiesSpreadPerShot);
            writer.Write(DualiesSpreadRecoverPerSecond);
            writer.Write(DualiesJumpBias);
            writer.Write(DualiesJumpRecoverStartSeconds);
            writer.Write(DualiesJumpRecoverEndSeconds);
            writer.Write(DualiesTrailStartDistance);
            writer.Write(DualiesTrailCount);
            writer.Write(DualiesFootEvery);
            writer.Write(DualiesFootRadius);
            writer.Write(BlasterRepeatSeconds);
            writer.Write(BlasterPostSeconds);
            writer.Write(BlasterPlayerRadius);
            writer.Write(BlasterBrakeEndSpeed);
            writer.Write(BlasterBrakeDrag);
            writer.Write(BlasterBrakeGravity);
            writer.Write(BlasterTrailCount);
            writer.Write(WeaponPrefabAddress ?? "");
            writer.Write((int)FireMode);
            writer.Write(FireRate);
            writer.Write(ShotInk);
            writer.Write(StartSeconds);
            writer.Write(EmergeStartSeconds);
            writer.Write(InkRecoverLockSeconds);
            writer.Write(ShootMoveSpeed);
            writer.Write(BurstCount);
            writer.Write(BurstRecoverySeconds);
            writer.Write(SpeedMin);
            writer.Write(SpeedMax);
            writer.Write(ProjectileGravity);
            writer.Write(Lifetime);
            writer.Write(CollisionRadius);
            writer.Write(SpreadDegrees);
            writer.Write(StraightSeconds);
            writer.Write(BrakeSeconds);
            writer.Write(BrakeSpeedMultiplier);
            writer.Write(JumpSpreadDegrees);
            writer.Write(LandingSpreadRecoverSeconds);
            writer.Write(EffectiveRange);
            writer.Write(Damage);
            writer.Write(DamageMin);
            writer.Write(DamageReduceStartSeconds);
            writer.Write(DamageReduceEndSeconds);
            writer.Write(PaintRadiusMin);
            writer.Write(PaintRadiusMax);
            writer.Write(PaintHardness);
            writer.Write(PaintStrength);
            writer.Write(TrailSpacing);
            writer.Write(TrailRadiusMin);
            writer.Write(TrailRadiusMax);
            writer.Write(TrailMaxDrop);
            writer.Write(ChargeSeconds);
            writer.Write(ChargeMinDamage);
            writer.Write(ChargePartialMaxDamage);
            writer.Write(ChargeMinInk);
            writer.Write(ChargeMinRange);
            writer.Write(ChargeMinSpeed);
            writer.Write(ChargeMinSpread);
            writer.Write(ChargeMinJumpSpread);
            writer.Write(PelletCount);
            writer.Write((int)MuzzleMode);
            writer.Write(SemiBufferSeconds);
            writer.Write(SplatlingMinChargeSeconds);
            writer.Write(SplatlingFirstChargeSeconds);
            writer.Write(SplatlingFirstShootSeconds);
            writer.Write(SplatlingFullShootSeconds);
            writer.Write(SplatlingSlowChargeMultiplier);
            writer.Write(SplatlingChargeMoveSpeed);
            writer.Write(SplatlingChargeJumpSpeed);
            writer.Write(SplatlingPostSeconds);
            writer.Write(SplatlingPitchSpread);
            writer.Write(SplatlingSpreadBias);
            writer.Write(SplatlingSpeedBias);
            writer.Write(SplatlingFootEvery);
            writer.Write(SplatlingTrailCount);
            writer.Write(SplatlingFootRadius);
            writer.Write(SplatlingPlayerRadius);
            writer.Write(SpreadExpandSeconds);
            writer.Write(SpreadRecoverSeconds);
            writer.Write(BaseSpreadDegrees);
            writer.Write(BaseJumpSpreadDegrees);
            writer.Write((int)MotionMode);
            writer.Write(BubbleVolleySeconds);
            writer.Write(BubbleIntervalSeconds);
            writer.Write(BubbleGroundBounces);
            writer.Write(BubbleMaxBounces);
            writer.Write(BubbleNormalRetention);
            writer.Write(BubbleTangentRetention);
            writer.Write(BubbleWallRetention);
            Ammo?.Write(writer);
        }
        public bool SameValues(WeaponRuntimeConfig other)
        {
            if (other == null || !Ammo.SameValues(other.Ammo)) return false;
            using var a = new MemoryStream(); using var b = new MemoryStream();
            using (var wa = new BinaryWriter(a, System.Text.Encoding.UTF8, true)) Write(wa);
            using (var wb = new BinaryWriter(b, System.Text.Encoding.UTF8, true)) other.Write(wb);
            return a.ToArray().AsSpan().SequenceEqual(b.ToArray());
        }
        public bool RequiresRestart(WeaponRuntimeConfig other) => other == null ||
            ShooterDetails != other.ShooterDetails || ShooterSplitNum != other.ShooterSplitNum || ShooterPostSeconds != other.ShooterPostSeconds ||
            ExplosherPostSeconds != other.ExplosherPostSeconds || ExplosherMoveLimitSeconds != other.ExplosherMoveLimitSeconds ||
            BlasterRepeatSeconds != other.BlasterRepeatSeconds || BlasterPostSeconds != other.BlasterPostSeconds ||
            ReferenceRules != other.ReferenceRules || ReferenceSpreadEnabled != other.ReferenceSpreadEnabled || MotionMode != other.MotionMode || BubbleVolleySeconds != other.BubbleVolleySeconds || BubbleIntervalSeconds != other.BubbleIntervalSeconds || WeaponPrefabAddress != other.WeaponPrefabAddress || FireMode != other.FireMode || FireRate != other.FireRate || ShotInk != other.ShotInk || StartSeconds != other.StartSeconds || EmergeStartSeconds != other.EmergeStartSeconds || InkRecoverLockSeconds != other.InkRecoverLockSeconds || BurstCount != other.BurstCount || BurstRecoverySeconds != other.BurstRecoverySeconds || ChargeSeconds != other.ChargeSeconds || ChargeMinInk != other.ChargeMinInk || PelletCount != other.PelletCount || MuzzleMode != other.MuzzleMode || SemiBufferSeconds != other.SemiBufferSeconds || SplatlingMinChargeSeconds != other.SplatlingMinChargeSeconds || SplatlingFirstChargeSeconds != other.SplatlingFirstChargeSeconds || SplatlingFirstShootSeconds != other.SplatlingFirstShootSeconds || SplatlingFullShootSeconds != other.SplatlingFullShootSeconds || SplatlingSlowChargeMultiplier != other.SplatlingSlowChargeMultiplier || SplatlingPostSeconds != other.SplatlingPostSeconds;
    }
}
