using System;
using System.IO;

namespace Splatoon.Config
{
    /// <summary>Immutable values shared by simulation and the shots emitted under this configuration.</summary>
    public sealed class WeaponRuntimeConfig
    {
        public readonly string WeaponPrefabAddress;
        public readonly int FireMode;
        public readonly float FireRate;
        public readonly float ShotInk;
        public readonly int StartFrames;
        public readonly int EmergeStartFrames;
        public readonly int InkRecoverLockFrames;
        public readonly float ShootMoveSpeed;
        public readonly int BurstCount;
        public readonly int BurstRecoveryFrames;
        public readonly float SpeedMin;
        public readonly float SpeedMax;
        public readonly float ProjectileGravity;
        public readonly float Lifetime;
        public readonly float CollisionRadius;
        public readonly float SpreadDegrees;
        public readonly int StraightFrames;
        public readonly int BrakeFrames;
        public readonly float BrakeSpeedMultiplier;
        public readonly float JumpSpreadDegrees;
        public readonly int SpreadRecoverFrames;
        public readonly float EffectiveRange;
        public readonly float Damage;
        public readonly float DamageMin;
        public readonly int DamageReduceStartFrames;
        public readonly int DamageReduceEndFrames;
        public readonly float PaintRadiusMin;
        public readonly float PaintRadiusMax;
        public readonly float PaintHardness;
        public readonly float PaintStrength;
        public readonly float TrailSpacing;
        public readonly float TrailRadiusMin;
        public readonly float TrailRadiusMax;
        public readonly float TrailMaxDrop;
        public readonly int ChargeFrames;
        public readonly float ChargeMinDamage;
        public readonly float ChargePartialMaxDamage;
        public readonly float ChargeMinInk;
        public readonly float ChargeMinRange;
        public readonly float ChargeMinSpeed;
        public readonly float ChargeMinSpread;
        public readonly float ChargeMinJumpSpread;
        public readonly int PelletCount;
        public readonly int MuzzleMode;
        public readonly int SemiBufferFrames;
        public readonly int SplatlingMinChargeFrames;
        public readonly int SplatlingFirstChargeFrames;
        public readonly int SplatlingFirstShootFrames;
        public readonly int SplatlingFullShootFrames;
        public readonly float SplatlingSlowChargeMultiplier;
        public readonly float SplatlingChargeMoveSpeed;
        public readonly float SplatlingChargeJumpSpeed;
        public readonly int SplatlingPostFrames;
        public readonly float SplatlingPitchSpread;
        public readonly float SplatlingSpreadBias;
        public readonly float SplatlingSpeedBias;
        public readonly int SplatlingFootEvery;
        public readonly int SplatlingTrailCount;
        public readonly float SplatlingFootRadius;
        public readonly float SplatlingPlayerRadius;
        public readonly float SpreadExpandSeconds;
        public readonly float SpreadRecoverSeconds;
        public readonly float BaseSpreadDegrees;
        public readonly float BaseJumpSpreadDegrees;
        public WeaponRuntimeConfig(WeaponConfigAsset source)
        {
            WeaponPrefabAddress = source.weaponPrefabAddress;
            FireMode = source.fireMode;
            FireRate = source.fireRate;
            ShotInk = source.shotInk;
            StartFrames = source.startFrames;
            EmergeStartFrames = source.emergeStartFrames;
            InkRecoverLockFrames = source.inkRecoverLockFrames;
            ShootMoveSpeed = source.shootMoveSpeed;
            BurstCount = source.burstCount;
            BurstRecoveryFrames = source.burstRecoveryFrames;
            SpeedMin = source.speedMin;
            SpeedMax = source.speedMax;
            ProjectileGravity = source.projectileGravity;
            Lifetime = source.lifetime;
            CollisionRadius = source.collisionRadius;
            SpreadDegrees = source.spreadDegrees;
            StraightFrames = source.straightFrames;
            BrakeFrames = source.brakeFrames;
            BrakeSpeedMultiplier = source.brakeSpeedMultiplier;
            JumpSpreadDegrees = source.jumpSpreadDegrees;
            SpreadRecoverFrames = source.spreadRecoverFrames;
            EffectiveRange = source.effectiveRange;
            Damage = source.damage;
            DamageMin = source.damageMin;
            DamageReduceStartFrames = source.damageReduceStartFrames;
            DamageReduceEndFrames = source.damageReduceEndFrames;
            PaintRadiusMin = source.paintRadiusMin;
            PaintRadiusMax = source.paintRadiusMax;
            PaintHardness = source.paintHardness;
            PaintStrength = source.paintStrength;
            TrailSpacing = source.trailSpacing;
            TrailRadiusMin = source.trailRadiusMin;
            TrailRadiusMax = source.trailRadiusMax;
            TrailMaxDrop = source.trailMaxDrop;
            ChargeFrames = source.chargeFrames;
            ChargeMinDamage = source.chargeMinDamage;
            ChargePartialMaxDamage = source.chargePartialMaxDamage;
            ChargeMinInk = source.chargeMinInk;
            ChargeMinRange = source.chargeMinRange;
            ChargeMinSpeed = source.chargeMinSpeed;
            ChargeMinSpread = source.chargeMinSpread;
            ChargeMinJumpSpread = source.chargeMinJumpSpread;
            PelletCount = source.pelletCount;
            MuzzleMode = source.muzzleMode;
            SemiBufferFrames = source.semiBufferFrames;
            SplatlingMinChargeFrames = source.splatlingMinChargeFrames;
            SplatlingFirstChargeFrames = source.splatlingFirstChargeFrames;
            SplatlingFirstShootFrames = source.splatlingFirstShootFrames;
            SplatlingFullShootFrames = source.splatlingFullShootFrames;
            SplatlingSlowChargeMultiplier = source.splatlingSlowChargeMultiplier;
            SplatlingChargeMoveSpeed = source.splatlingChargeMoveSpeed;
            SplatlingChargeJumpSpeed = source.splatlingChargeJumpSpeed;
            SplatlingPostFrames = source.splatlingPostFrames;
            SplatlingPitchSpread = source.splatlingPitchSpread;
            SplatlingSpreadBias = source.splatlingSpreadBias;
            SplatlingSpeedBias = source.splatlingSpeedBias;
            SplatlingFootEvery = source.splatlingFootEvery;
            SplatlingTrailCount = source.splatlingTrailCount;
            SplatlingFootRadius = source.splatlingFootRadius;
            SplatlingPlayerRadius = source.splatlingPlayerRadius;
            SpreadExpandSeconds = source.spreadExpandSeconds;
            SpreadRecoverSeconds = source.spreadRecoverSeconds;
            BaseSpreadDegrees = source.baseSpreadDegrees;
            BaseJumpSpreadDegrees = source.baseJumpSpreadDegrees;
        }
        public void Write(BinaryWriter writer)
        {
            writer.Write(WeaponPrefabAddress ?? "");
            writer.Write(FireMode);
            writer.Write(FireRate);
            writer.Write(ShotInk);
            writer.Write(StartFrames);
            writer.Write(EmergeStartFrames);
            writer.Write(InkRecoverLockFrames);
            writer.Write(ShootMoveSpeed);
            writer.Write(BurstCount);
            writer.Write(BurstRecoveryFrames);
            writer.Write(SpeedMin);
            writer.Write(SpeedMax);
            writer.Write(ProjectileGravity);
            writer.Write(Lifetime);
            writer.Write(CollisionRadius);
            writer.Write(SpreadDegrees);
            writer.Write(StraightFrames);
            writer.Write(BrakeFrames);
            writer.Write(BrakeSpeedMultiplier);
            writer.Write(JumpSpreadDegrees);
            writer.Write(SpreadRecoverFrames);
            writer.Write(EffectiveRange);
            writer.Write(Damage);
            writer.Write(DamageMin);
            writer.Write(DamageReduceStartFrames);
            writer.Write(DamageReduceEndFrames);
            writer.Write(PaintRadiusMin);
            writer.Write(PaintRadiusMax);
            writer.Write(PaintHardness);
            writer.Write(PaintStrength);
            writer.Write(TrailSpacing);
            writer.Write(TrailRadiusMin);
            writer.Write(TrailRadiusMax);
            writer.Write(TrailMaxDrop);
            writer.Write(ChargeFrames);
            writer.Write(ChargeMinDamage);
            writer.Write(ChargePartialMaxDamage);
            writer.Write(ChargeMinInk);
            writer.Write(ChargeMinRange);
            writer.Write(ChargeMinSpeed);
            writer.Write(ChargeMinSpread);
            writer.Write(ChargeMinJumpSpread);
            writer.Write(PelletCount);
            writer.Write(MuzzleMode);
            writer.Write(SemiBufferFrames);
            writer.Write(SplatlingMinChargeFrames);
            writer.Write(SplatlingFirstChargeFrames);
            writer.Write(SplatlingFirstShootFrames);
            writer.Write(SplatlingFullShootFrames);
            writer.Write(SplatlingSlowChargeMultiplier);
            writer.Write(SplatlingChargeMoveSpeed);
            writer.Write(SplatlingChargeJumpSpeed);
            writer.Write(SplatlingPostFrames);
            writer.Write(SplatlingPitchSpread);
            writer.Write(SplatlingSpreadBias);
            writer.Write(SplatlingSpeedBias);
            writer.Write(SplatlingFootEvery);
            writer.Write(SplatlingTrailCount);
            writer.Write(SplatlingFootRadius);
            writer.Write(SplatlingPlayerRadius);
            writer.Write(SpreadExpandSeconds);
            writer.Write(SpreadRecoverSeconds);
            writer.Write(BaseSpreadDegrees);
            writer.Write(BaseJumpSpreadDegrees);
        }
        public bool SameValues(WeaponRuntimeConfig other)
        {
            if (other == null) return false;
            using var a = new MemoryStream(); using var b = new MemoryStream();
            using (var wa = new BinaryWriter(a, System.Text.Encoding.UTF8, true)) Write(wa);
            using (var wb = new BinaryWriter(b, System.Text.Encoding.UTF8, true)) other.Write(wb);
            return a.ToArray().AsSpan().SequenceEqual(b.ToArray());
        }
        public bool RequiresRestart(WeaponRuntimeConfig other) => other == null ||
            WeaponPrefabAddress != other.WeaponPrefabAddress || FireMode != other.FireMode || FireRate != other.FireRate || ShotInk != other.ShotInk || StartFrames != other.StartFrames || EmergeStartFrames != other.EmergeStartFrames || InkRecoverLockFrames != other.InkRecoverLockFrames || BurstCount != other.BurstCount || BurstRecoveryFrames != other.BurstRecoveryFrames || ChargeFrames != other.ChargeFrames || ChargeMinInk != other.ChargeMinInk || PelletCount != other.PelletCount || MuzzleMode != other.MuzzleMode || SemiBufferFrames != other.SemiBufferFrames || SplatlingMinChargeFrames != other.SplatlingMinChargeFrames || SplatlingFirstChargeFrames != other.SplatlingFirstChargeFrames || SplatlingFirstShootFrames != other.SplatlingFirstShootFrames || SplatlingFullShootFrames != other.SplatlingFullShootFrames || SplatlingSlowChargeMultiplier != other.SplatlingSlowChargeMultiplier || SplatlingPostFrames != other.SplatlingPostFrames;
    }
}
