using System;
using System.IO;

namespace Splatoon.Config
{
    /// <summary>Immutable values shared by simulation and the shots emitted under this configuration.</summary>
    public sealed class WeaponRuntimeConfig
    {
        public readonly string WeaponPrefabAddress;
        public readonly WeaponFireMode FireMode;
        public readonly float FireRate;
        public readonly float ShotInk;
        public readonly double StartSeconds;
        public readonly double EmergeStartSeconds;
        public readonly double InkRecoverLockSeconds;
        public readonly float ShootMoveSpeed;
        public readonly int BurstCount;
        public readonly double BurstRecoverySeconds;
        public readonly float SpeedMin;
        public readonly float SpeedMax;
        public readonly float ProjectileGravity;
        public readonly float Lifetime;
        public readonly float CollisionRadius;
        public readonly float SpreadDegrees;
        public readonly double StraightSeconds;
        public readonly double BrakeSeconds;
        public readonly float BrakeSpeedMultiplier;
        public readonly float JumpSpreadDegrees;
        public readonly double LandingSpreadRecoverSeconds;
        public readonly float EffectiveRange;
        public readonly float Damage;
        public readonly float DamageMin;
        public readonly double DamageReduceStartSeconds;
        public readonly double DamageReduceEndSeconds;
        public readonly float PaintRadiusMin;
        public readonly float PaintRadiusMax;
        public readonly float PaintHardness;
        public readonly float PaintStrength;
        public readonly float TrailSpacing;
        public readonly float TrailRadiusMin;
        public readonly float TrailRadiusMax;
        public readonly float TrailMaxDrop;
        public readonly double ChargeSeconds;
        public readonly float ChargeMinDamage;
        public readonly float ChargePartialMaxDamage;
        public readonly float ChargeMinInk;
        public readonly float ChargeMinRange;
        public readonly float ChargeMinSpeed;
        public readonly float ChargeMinSpread;
        public readonly float ChargeMinJumpSpread;
        public readonly int PelletCount;
        public readonly WeaponMuzzleMode MuzzleMode;
        public readonly double SemiBufferSeconds;
        public readonly double SplatlingMinChargeSeconds;
        public readonly double SplatlingFirstChargeSeconds;
        public readonly double SplatlingFirstShootSeconds;
        public readonly double SplatlingFullShootSeconds;
        public readonly float SplatlingSlowChargeMultiplier;
        public readonly float SplatlingChargeMoveSpeed;
        public readonly float SplatlingChargeJumpSpeed;
        public readonly double SplatlingPostSeconds;
        public readonly float SplatlingPitchSpread;
        public readonly float SplatlingSpreadBias;
        public readonly float SplatlingSpeedBias;
        public readonly int SplatlingFootEvery;
        public readonly int SplatlingTrailCount;
        public readonly float SplatlingFootRadius;
        public readonly float SplatlingPlayerRadius;
        public readonly float SpreadExpandSeconds;
        public readonly float SpreadRecoverSeconds;
        public readonly float BaseSpreadDegrees;
        public readonly float BaseJumpSpreadDegrees;
        public readonly AmmoRuntimeConfig Ammo;
        public WeaponRuntimeConfig(WeaponConfigAsset source)
        {
            Ammo = new AmmoRuntimeConfig(source != null ? source.ammoConfig : null);
            WeaponPrefabAddress = source.weaponPrefabAddress;
            FireMode = source.fireMode;
            FireRate = source.fireRate;
            ShotInk = source.shotInk;
            StartSeconds = source.startSeconds;
            EmergeStartSeconds = source.emergeStartSeconds;
            InkRecoverLockSeconds = source.inkRecoverLockSeconds;
            ShootMoveSpeed = source.shootMoveSpeed;
            BurstCount = source.burstCount;
            BurstRecoverySeconds = source.burstRecoverySeconds;
            SpeedMin = source.speedMin;
            SpeedMax = source.speedMax;
            ProjectileGravity = source.projectileGravity;
            Lifetime = source.lifetime;
            CollisionRadius = source.collisionRadius;
            SpreadDegrees = source.spreadDegrees;
            StraightSeconds = source.straightSeconds;
            BrakeSeconds = source.brakeSeconds;
            BrakeSpeedMultiplier = source.brakeSpeedMultiplier;
            JumpSpreadDegrees = source.jumpSpreadDegrees;
            LandingSpreadRecoverSeconds = source.landingSpreadRecoverSeconds;
            EffectiveRange = source.effectiveRange;
            Damage = source.damage;
            DamageMin = source.damageMin;
            DamageReduceStartSeconds = source.damageReduceStartSeconds;
            DamageReduceEndSeconds = source.damageReduceEndSeconds;
            PaintRadiusMin = source.paintRadiusMin;
            PaintRadiusMax = source.paintRadiusMax;
            PaintHardness = source.paintHardness;
            PaintStrength = source.paintStrength;
            TrailSpacing = source.trailSpacing;
            TrailRadiusMin = source.trailRadiusMin;
            TrailRadiusMax = source.trailRadiusMax;
            TrailMaxDrop = source.trailMaxDrop;
            ChargeSeconds = source.chargeSeconds;
            ChargeMinDamage = source.chargeMinDamage;
            ChargePartialMaxDamage = source.chargePartialMaxDamage;
            ChargeMinInk = source.chargeMinInk;
            ChargeMinRange = source.chargeMinRange;
            ChargeMinSpeed = source.chargeMinSpeed;
            ChargeMinSpread = source.chargeMinSpread;
            ChargeMinJumpSpread = source.chargeMinJumpSpread;
            PelletCount = source.pelletCount;
            MuzzleMode = source.muzzleMode;
            SemiBufferSeconds = source.semiBufferSeconds;
            SplatlingMinChargeSeconds = source.splatlingMinChargeSeconds;
            SplatlingFirstChargeSeconds = source.splatlingFirstChargeSeconds;
            SplatlingFirstShootSeconds = source.splatlingFirstShootSeconds;
            SplatlingFullShootSeconds = source.splatlingFullShootSeconds;
            SplatlingSlowChargeMultiplier = source.splatlingSlowChargeMultiplier;
            SplatlingChargeMoveSpeed = source.splatlingChargeMoveSpeed;
            SplatlingChargeJumpSpeed = source.splatlingChargeJumpSpeed;
            SplatlingPostSeconds = source.splatlingPostSeconds;
            SplatlingPitchSpread = source.splatlingPitchSpread;
            SplatlingSpreadBias = source.splatlingSpreadBias;
            SplatlingSpeedBias = source.splatlingSpeedBias;
            SplatlingFootEvery = source.splatlingFootEvery;
            SplatlingTrailCount = source.splatlingTrailCount;
            SplatlingFootRadius = source.splatlingFootRadius;
            SplatlingPlayerRadius = source.splatlingPlayerRadius;
            SpreadExpandSeconds = source.spreadExpandSeconds;
            SpreadRecoverSeconds = source.spreadRecoverSeconds;
            BaseSpreadDegrees = source.baseSpreadDegrees;
            BaseJumpSpreadDegrees = source.baseJumpSpreadDegrees;
        }
        public void Write(BinaryWriter writer)
        {
            writer.Write(WeaponPrefabAddress ?? "");
            writer.Write((int)FireMode);
            writer.Write(FireRate);
            writer.Write(ShotInk);
            writer.Write(StartSeconds);
            writer.Write(EmergeStartSeconds);
            writer.Write(InkRecoverLockSeconds);
            writer.Write(ShootMoveSpeed);
            writer.Write(BurstCount);
            writer.Write(BurstRecoverySeconds);
            writer.Write(SpeedMin);
            writer.Write(SpeedMax);
            writer.Write(ProjectileGravity);
            writer.Write(Lifetime);
            writer.Write(CollisionRadius);
            writer.Write(SpreadDegrees);
            writer.Write(StraightSeconds);
            writer.Write(BrakeSeconds);
            writer.Write(BrakeSpeedMultiplier);
            writer.Write(JumpSpreadDegrees);
            writer.Write(LandingSpreadRecoverSeconds);
            writer.Write(EffectiveRange);
            writer.Write(Damage);
            writer.Write(DamageMin);
            writer.Write(DamageReduceStartSeconds);
            writer.Write(DamageReduceEndSeconds);
            writer.Write(PaintRadiusMin);
            writer.Write(PaintRadiusMax);
            writer.Write(PaintHardness);
            writer.Write(PaintStrength);
            writer.Write(TrailSpacing);
            writer.Write(TrailRadiusMin);
            writer.Write(TrailRadiusMax);
            writer.Write(TrailMaxDrop);
            writer.Write(ChargeSeconds);
            writer.Write(ChargeMinDamage);
            writer.Write(ChargePartialMaxDamage);
            writer.Write(ChargeMinInk);
            writer.Write(ChargeMinRange);
            writer.Write(ChargeMinSpeed);
            writer.Write(ChargeMinSpread);
            writer.Write(ChargeMinJumpSpread);
            writer.Write(PelletCount);
            writer.Write((int)MuzzleMode);
            writer.Write(SemiBufferSeconds);
            writer.Write(SplatlingMinChargeSeconds);
            writer.Write(SplatlingFirstChargeSeconds);
            writer.Write(SplatlingFirstShootSeconds);
            writer.Write(SplatlingFullShootSeconds);
            writer.Write(SplatlingSlowChargeMultiplier);
            writer.Write(SplatlingChargeMoveSpeed);
            writer.Write(SplatlingChargeJumpSpeed);
            writer.Write(SplatlingPostSeconds);
            writer.Write(SplatlingPitchSpread);
            writer.Write(SplatlingSpreadBias);
            writer.Write(SplatlingSpeedBias);
            writer.Write(SplatlingFootEvery);
            writer.Write(SplatlingTrailCount);
            writer.Write(SplatlingFootRadius);
            writer.Write(SplatlingPlayerRadius);
            writer.Write(SpreadExpandSeconds);
            writer.Write(SpreadRecoverSeconds);
            writer.Write(BaseSpreadDegrees);
            writer.Write(BaseJumpSpreadDegrees);
            Ammo?.Write(writer);
        }
        public bool SameValues(WeaponRuntimeConfig other)
        {
            if (other == null) return false;
            using var a = new MemoryStream(); using var b = new MemoryStream();
            using (var wa = new BinaryWriter(a, System.Text.Encoding.UTF8, true)) Write(wa);
            using (var wb = new BinaryWriter(b, System.Text.Encoding.UTF8, true)) other.Write(wb);
            return a.ToArray().AsSpan().SequenceEqual(b.ToArray());
        }
        public bool RequiresRestart(WeaponRuntimeConfig other) => other == null ||
            WeaponPrefabAddress != other.WeaponPrefabAddress || FireMode != other.FireMode || FireRate != other.FireRate || ShotInk != other.ShotInk || StartSeconds != other.StartSeconds || EmergeStartSeconds != other.EmergeStartSeconds || InkRecoverLockSeconds != other.InkRecoverLockSeconds || BurstCount != other.BurstCount || BurstRecoverySeconds != other.BurstRecoverySeconds || ChargeSeconds != other.ChargeSeconds || ChargeMinInk != other.ChargeMinInk || PelletCount != other.PelletCount || MuzzleMode != other.MuzzleMode || SemiBufferSeconds != other.SemiBufferSeconds || SplatlingMinChargeSeconds != other.SplatlingMinChargeSeconds || SplatlingFirstChargeSeconds != other.SplatlingFirstChargeSeconds || SplatlingFirstShootSeconds != other.SplatlingFirstShootSeconds || SplatlingFullShootSeconds != other.SplatlingFullShootSeconds || SplatlingSlowChargeMultiplier != other.SplatlingSlowChargeMultiplier || SplatlingPostSeconds != other.SplatlingPostSeconds || Ammo?.AmmoId != other.Ammo?.AmmoId || Ammo?.ExplosionEnabled != other.Ammo?.ExplosionEnabled || Ammo?.ExplosionRadius != other.Ammo?.ExplosionRadius || Ammo?.ExplosionDamage != other.Ammo?.ExplosionDamage || Ammo?.ExplosionPaint != other.Ammo?.ExplosionPaint || Ammo?.ExplosionPaintRadiusMin != other.Ammo?.ExplosionPaintRadiusMin || Ammo?.ExplosionPaintRadiusMax != other.Ammo?.ExplosionPaintRadiusMax;
    }
}
